all: \
	01_peldany_vektor \
	02_pointer_vektor_de_nem_virtualis \
	03_virtualisan \
	04_virtualisan_memory_safe-en \
	05_virtualis_de_nem_pointer \
	06_union_tipus

01_peldany_vektor: 01_peldany_vektor.cc
	g++ -Wall -o 01_peldany_vektor 01_peldany_vektor.cc

02_pointer_vektor_de_nem_virtualis: 02_pointer_vektor_de_nem_virtualis.cc
	g++ -Wall -o 02_pointer_vektor_de_nem_virtualis 02_pointer_vektor_de_nem_virtualis.cc

03_virtualisan: 03_virtualisan.cc
	g++ -Wall -o 03_virtualisan 03_virtualisan.cc

04_virtualisan_memory_safe-en: 04_virtualisan_memory_safe-en.cc
	g++ -Wall -o 04_virtualisan_memory_safe-en 04_virtualisan_memory_safe-en.cc

05_virtualis_de_nem_pointer: 05_virtualis_de_nem_pointer.cc
	g++ -Wall -o 05_virtualis_de_nem_pointer 05_virtualis_de_nem_pointer.cc

06_union_tipus: 06_union_tipus.cc
	g++ -g -O0 -Wall --std=c++23 -o 06_union_tipus 06_union_tipus.cc
